name: uda2
dependencies:
  - notebook=6.2.0
  - ipython=7.21.0
  - cookiecutter=1.7.2
  - matplotlib=3.3.4
  - pandas=1.2.3
  - pip=20.3.3
  - pip:
      - numpy==1.20.0
      - hydra-core==1.0.6
      - mlflow==1.14.1
      - jupyterlab==3.0.10 
      - wandb==0.10.31
